name: Tests

concurrency: production

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install Dependencies
      run: npm install
    - name: Run Tests
      run: npm test
    - name: Run Deploy Script
    - run: npm run deploy