name: PWA
on: push
jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install Dependencies
      run: npm install
    - name: Start Firebase and Run Tests
      run: npm test
